blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Please support my work on Jinx and my other Emacs packages"
    url: https://github.com/sponsors/minad
    about: Thanks! Your support helps dedicating time to project maintenance and development.
  - name: "ğŸ’¡ Suggest a feature â Please create a discussion"
    url: https://github.com/minad/jinx/discussions/categories/ideas
    about: Start a new discussion suggesting an improvement or a feature.
  - name: "ğŸ§‘â€ğŸ¤â€ğŸ§‘ Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please be kind and support others.
  - name: "ğŸ¤“ Ask the maintainer for support â Please create a discussion"
    url: https://github.com/minad/jinx/discussions/categories/q-a
    about: Please keep in mind that my bandwidth is limited.
  - name: "ğŸ” Search through old issues or discussions"
    url: https://github.com/search?q=repo%3Aminad%2Fjinx&type=issues
    about: The same question may have been asked before.
  - name: "ğŸ“ Jinx wiki"
    url: https://github.com/minad/jinx/wiki
    about: Additional configuration tips are covered there. Feel free to edit!
  - name: "ğŸ“– Jinx manual"
    url: https://github.com/minad/jinx/blob/main/README.org
    about: The manual covers the basic setup and workflow.
